name: Python Flask GitHub action for docker registry 
on:
  workflow_dispatch:

# Env variable
env:
  DOCKER_USER: sselluos
  DOCKER_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
  AWS_PRIVATE_KEY: ${{secrets.AWS_EC2_PRIVATE_KEY}}
  REPO_NAME: flaskproject
  EC2_PUBLIC_IP: 50.18.236.167
  TAG_VAR: latest

jobs:
  build:  
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v4 
    - name: docker login
      run: | 
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Get current date 
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    - name: Build the Docker image 
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_TOKEN }}
    - name: Set permissions for private key
      run: |
        echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
    - name: Pull Docker image
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${EC2_PUBLIC_IP} "sudo docker pull $DOCKER_USER/$REPO_NAME:$TAG_VAR"


