name: Create dynamodb table

on:
  workflow_dispatch:

env:
  TABLE_NAME: terraform-up-and-running-locks-maris

jobs:
  create_dynamodb:
    runs-on: ubuntu-latest

    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1  # Change this to your desired region

      - name: Create dynamodb table
        run: aws dynamodb create-table --table-name ${TABLE_NAME} --provisioned-throughput ReadCapacityUnits=100,WriteCapacityUnits=100 --attribute-definitions AttributeName=LockID,AttributeType=S --key-schema AttributeName=LockID,KeyType=HASH --tags Key=Owner,Value="Maris Liepins"